# Generated by Django 5.1.15 on 2026-08-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(db_index=True, max_length=255)),
                ('business_sector', models.CharField(db_index=True, max_length=255)),
                ('region_id', models.CharField(db_index=True, max_length=100)),
                ('region_name', models.CharField(max_length=255)),
                ('business_profile', models.JSONField(default=dict, help_text='Business details provided during request')),
                ('ai_screening', models.JSONField(default=dict, help_text='Preliminary AI screening result')),
                ('mimic_data', models.JSONField(default=dict, help_text='MIMIC causes and indicators snapshot')),
                ('notes', models.TextField(blank=True, help_text='Inline summary / quick-take notes')),
                ('executive_summary', models.TextField(blank=True)),
                ('causes_analysis', models.TextField(blank=True)),
                ('indicators_analysis', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('estimated_index', models.IntegerField(blank=True, null=True)),
                ('confidence_percent', models.IntegerField(blank=True, null=True)),
                ('key_risk_factors', models.JSONField(default=list)),
                ('model_used', models.CharField(default='gemini-2.5-flash', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
