import { jsPDF } from "jspdf"

const MARGIN = 48

function createLayout(doc) {
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const contentWidth = pageWidth - MARGIN * 2
  let y = MARGIN

  function ensureSpace(needed) {
    if (y + needed > pageHeight - MARGIN) {
      doc.addPage()
      y = MARGIN
    }
  }

  function spacer(height = 10) {
    y += height
  }

  function heading(text, size = 13) {
    ensureSpace(size + 12)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(size)
    doc.text(text, MARGIN, y)
    y += size + 8
  }

  function paragraph(text, size = 10) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(size)
    const lines = doc.splitTextToSize(text, contentWidth)
    for (const line of lines) {
      ensureSpace(size + 3)
      doc.text(line, MARGIN, y)
      y += size + 3
    }
    spacer(8)
  }

  function keyValueLine(label, value, size = 9) {
    ensureSpace(size + 4)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(size)
    doc.text(label, MARGIN, y)
    doc.setFont("helvetica", "normal")
    doc.text(String(value), MARGIN + 150, y)
    y += size + 4
  }

  function bullet(text, size = 10) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(size)
    const lines = doc.splitTextToSize(`•  ${text}`, contentWidth - 10)
    for (const line of lines) {
      ensureSpace(size + 3)
      doc.text(line, MARGIN + 4, y)
      y += size + 3
    }
  }

  return { ensureSpace, spacer, heading, paragraph, keyValueLine, bullet, contentWidth, get y() { return y }, set y(v) { y = v } }
}

function formatVariables(variables) {
  return variables.map((v) => `${v.label}: ${v.value} ${v.unit}`)
}

export function downloadShadowEconomyReportPdf({ business, region, aiResult, report }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" })
  const L = createLayout(doc)

  doc.setFont("helvetica", "bold")
  doc.setFontSize(18)
  doc.text("Shadow Economy Risk Report", MARGIN, L.y)
  L.y += 26

  doc.setFont("helvetica", "normal")
  doc.setFontSize(10)
  doc.setTextColor(90)
  doc.text(`${business.name} MCHJ  •  ${region.name}`, MARGIN, L.y)
  L.y += 14
  doc.text(`Generated ${new Date(report.generatedAt).toLocaleString("en-US")}`, MARGIN, L.y)
  doc.setTextColor(0)
  L.spacer(20)

  L.heading("Business Profile")
  L.keyValueLine("Sector", business.sector)
  L.keyValueLine("Region", region.name)
  L.keyValueLine("Employees", business.employees)
  L.keyValueLine("Revenue", `${business.revenue.toLocaleString("en-US")} UZS`)
  L.keyValueLine("Registered", business.registered)
  L.keyValueLine("Status", business.status)
  L.spacer(14)

  L.heading("Preliminary AI Screening")
  L.keyValueLine("Score", `${aiResult.score} / 10`)
  L.keyValueLine("Probability", `${aiResult.probability}%`)
  L.keyValueLine("Flagged", aiResult.flagged ? "Yes" : "No")
  L.spacer(14)

  L.heading("Notes")
  L.paragraph(report.notes)

  L.heading("Executive Summary")
  L.paragraph(report.executiveSummary)

  L.heading("Causes Analysis (MIMIC)")
  L.paragraph(report.causesAnalysis)
  L.ensureSpace(60)
  doc.setFont("helvetica", "italic")
  doc.setFontSize(8.5)
  doc.setTextColor(110)
  for (const line of formatVariables(report.mimicData.causes)) {
    L.ensureSpace(12)
    doc.text(line, MARGIN, L.y)
    L.y += 12
  }
  doc.setTextColor(0)
  L.spacer(14)

  L.heading("Indicators Analysis (MIMIC)")
  L.paragraph(report.indicatorsAnalysis)
  doc.setFont("helvetica", "italic")
  doc.setFontSize(8.5)
  doc.setTextColor(110)
  for (const line of formatVariables(report.mimicData.indicators)) {
    L.ensureSpace(12)
    doc.text(line, MARGIN, L.y)
    L.y += 12
  }
  doc.setTextColor(0)
  L.spacer(14)

  L.heading("Key Risk Factors")
  for (const factor of report.keyRiskFactors) {
    L.bullet(factor)
  }
  L.spacer(14)

  L.heading("Conclusion")
  L.paragraph(report.conclusion)
  L.keyValueLine("Estimated shadow economy index", `${report.estimatedIndex} / 10`)
  L.keyValueLine("Confidence", `${report.confidencePercent}%`)
  L.spacer(20)

  L.ensureSpace(40)
  doc.setFont("helvetica", "italic")
  doc.setFontSize(8)
  doc.setTextColor(130)
  L.paragraph(
    "This report was generated by an AI model (Gemini) from simulated MIMIC macro data and a simulated preliminary screening. It is a product demonstration, not a verified statistical estimate or an official government finding.",
    8
  )

  const filename = `${business.id || business.name.toLowerCase().replace(/\s+/g, "-")}-shadow-economy-report.pdf`
  doc.save(filename)
}
