# Generated by Django 5.1.15 on 2026-08-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('retail', 'Retail & Groceries'), ('food_service', 'Food Service & Restaurants'), ('services', 'Professional & Consumer Services'), ('trade', 'Wholesale & Trade'), ('construction', 'Construction & Contracting')], db_index=True, max_length=50)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('registered', models.BooleanField(default=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['business_id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=30, unique=True)),
                ('seller_name', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('est_monthly_ad_spend', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('follower_count', models.IntegerField(default=0)),
                ('matched_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_listings', to='radar.business')),
            ],
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_ratio', models.FloatField(default=1.0)),
                ('z_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('tier', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], db_index=True, default='low', max_length=10)),
                ('sector_avg_gap', models.FloatField(default=1.0)),
                ('est_undeclared_min', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('est_undeclared_max', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('report_text', models.TextField(blank=True, null=True)),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='radar.business')),
            ],
            options={
                'ordering': ['-risk_score', '-gap_ratio'],
            },
        ),
        migrations.CreateModel(
            name='TaxFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('declared_revenue', models.DecimalField(decimal_places=2, max_digits=16)),
                ('declared_employees', models.IntegerField(default=1)),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_filings', to='radar.business')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('business', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TransactionSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('pos_ewallet_volume', models.DecimalField(decimal_places=2, max_digits=16)),
                ('transaction_count', models.IntegerField(default=0)),
                ('avg_transaction_size', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_signals', to='radar.business')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('business', 'month')},
            },
        ),
    ]
