// Mock data — fictional companies for prototype purposes only.
import { INDUSTRIES } from "@/lib/industries"

export const SECTORS = INDUSTRIES.map((industry) => industry.name)

export const BUSINESSES = [
  {
    id: "oltin-vodiy-savdo",
    name: "Oltin Vodiy Savdo",
    regionId: "tashkent-city",
    sector: "Wholesale & Retail Trade",
    stir: "301245678",
    registered: "2014-03-11",
    employees: 42,
    revenue: 6_400_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Oltin Vodiy Savdo MCHJ distributes consumer electronics and household goods to retail partners across Tashkent. The company has operated since 2014 and reports a stable, year-round workforce.",
  },
  {
    id: "chinor-it-solutions",
    name: "Chinor IT Solutions",
    regionId: "tashkent-city",
    sector: "Technology & AI",
    stir: "302356789",
    registered: "2019-07-02",
    employees: 27,
    revenue: 3_100_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Chinor IT Solutions MCHJ builds custom software and provides IT infrastructure support for mid-size enterprises. Revenue is contract-based and predominantly settled through bank transfer.",
  },
  {
    id: "poytaxt-logistika",
    name: "Poytaxt Logistika Xizmatlari",
    regionId: "tashkent-city",
    sector: "Logistics & Transport",
    stir: "303467890",
    registered: "2016-11-20",
    employees: 68,
    revenue: 9_800_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Poytaxt Logistika Xizmatlari MCHJ operates a freight fleet serving warehouses in and around the capital. The company subcontracts a portion of its haulage capacity to independent drivers.",
  },
  {
    id: "toshkent-metall-profil",
    name: "Toshkent Metall Profil",
    regionId: "tashkent-city",
    sector: "Construction & Materials",
    stir: "304578901",
    registered: "2012-05-09",
    employees: 95,
    revenue: 14_200_000_000,
    status: "Under Review",
    baselineRisk: "Moderate",
    description:
      "Toshkent Metall Profil MCHJ manufactures steel roofing and framing components for the residential construction market. Production volume has grown steadily over the past three reporting years.",
  },
  {
    id: "bekobod-sement",
    name: "Bekobod Sement Ishlab Chiqarish",
    regionId: "tashkent-region",
    sector: "Construction & Materials",
    stir: "305689012",
    registered: "2010-02-17",
    employees: 210,
    revenue: 22_500_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Bekobod Sement Ishlab Chiqarish MCHJ is a regional cement producer supplying construction firms throughout Tashkent Region. It is one of the larger declared employers in its district.",
  },
  {
    id: "chirchiq-kimyo",
    name: "Chirchiq Kimyo Sanoat",
    regionId: "tashkent-region",
    sector: "Manufacturing",
    stir: "306790123",
    registered: "2011-09-01",
    employees: 134,
    revenue: 17_900_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Chirchiq Kimyo Sanoat MCHJ produces industrial cleaning agents and agricultural chemicals. Utility consumption records are reviewed periodically due to the energy-intensive nature of the sector.",
  },
  {
    id: "yashnobod-elektronika",
    name: "Yashnobod Elektronika Savdo",
    regionId: "tashkent-region",
    sector: "Wholesale & Retail Trade",
    stir: "307801234",
    registered: "2017-01-25",
    employees: 19,
    revenue: 2_650_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Yashnobod Elektronika Savdo MCHJ operates a chain of small electronics retail outlets. Card-payment terminal usage is in line with the regional retail average.",
  },
  {
    id: "andijon-mashinasozlik",
    name: "Andijon Mashinasozlik Zavodi",
    regionId: "andijan",
    sector: "Manufacturing",
    stir: "308912345",
    registered: "2009-06-14",
    employees: 187,
    revenue: 19_300_000_000,
    status: "Active",
    baselineRisk: "Elevated",
    description:
      "Andijon Mashinasozlik Zavodi MCHJ manufactures spare parts for agricultural machinery. Several related-party entities share directors with this business.",
  },
  {
    id: "fargona-vodiysi-tekstil",
    name: "Farg'ona Vodiysi Tekstil",
    regionId: "andijan",
    sector: "Textile & Apparel",
    stir: "309023456",
    registered: "2015-04-08",
    employees: 156,
    revenue: 11_400_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Farg'ona Vodiysi Tekstil MCHJ spins and weaves cotton yarn for domestic garment producers. Seasonal headcount varies with raw cotton availability.",
  },
  {
    id: "andijon-meva-konserva",
    name: "Andijon Meva Konserva",
    regionId: "andijan",
    sector: "Food Processing",
    stir: "310134567",
    registered: "2013-08-30",
    employees: 88,
    revenue: 8_700_000_000,
    status: "Under Review",
    baselineRisk: "Elevated",
    description:
      "Andijon Meva Konserva MCHJ cans and preserves regionally grown fruit for domestic distribution. Declared output has been flagged for a follow-up production audit.",
  },
  {
    id: "buxoro-neft-gaz-servis",
    name: "Buxoro Neft Gaz Servis",
    regionId: "bukhara",
    sector: "Energy & Utilities",
    stir: "311245678",
    registered: "2008-12-05",
    employees: 143,
    revenue: 26_800_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Buxoro Neft Gaz Servis MCHJ provides maintenance and support services to regional gas distribution infrastructure. The business holds long-term service contracts with municipal utilities.",
  },
  {
    id: "buxoro-gilam-fabrikasi",
    name: "Buxoro Gilam Fabrikasi",
    regionId: "bukhara",
    sector: "Textile & Apparel",
    stir: "312356789",
    registered: "2018-10-19",
    employees: 51,
    revenue: 4_300_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Buxoro Gilam Fabrikasi MCHJ hand-weaves and machine-finishes carpets for domestic and export sale. Export shipments are documented through customs declarations.",
  },
  {
    id: "margilon-ipak-karvoni",
    name: "Marg'ilon Ipak Karvoni",
    regionId: "fergana",
    sector: "Textile & Apparel",
    stir: "313467890",
    registered: "2014-02-22",
    employees: 76,
    revenue: 6_900_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Marg'ilon Ipak Karvoni MCHJ produces traditional silk fabric (atlas and adras) for domestic retailers and tourist markets. A portion of raw silk is sourced from smallholder producers.",
  },
  {
    id: "fargona-kimyo-zavodi",
    name: "Farg'ona Kimyo Zavodi",
    regionId: "fergana",
    sector: "Manufacturing",
    stir: "314578901",
    registered: "2010-07-13",
    employees: 201,
    revenue: 24_100_000_000,
    status: "Active",
    baselineRisk: "Elevated",
    description:
      "Farg'ona Kimyo Zavodi MCHJ manufactures mineral fertilizer for regional agricultural cooperatives. Reported wage levels sit below the sector average for comparable plants.",
  },
  {
    id: "qoqon-oziq-ovqat",
    name: "Qo'qon Oziq-Ovqat Sanoati",
    regionId: "fergana",
    sector: "Food Processing",
    stir: "315689012",
    registered: "2016-03-04",
    employees: 63,
    revenue: 5_500_000_000,
    status: "Active",
    baselineRisk: "Elevated",
    description:
      "Qo'qon Oziq-Ovqat Sanoati MCHJ processes and packages dried fruit and nuts for wholesale distribution. Bank-settled revenue has declined as a share of total turnover over the past year.",
  },
  {
    id: "jizzax-agro-eksport",
    name: "Jizzax Agro Eksport",
    regionId: "jizzakh",
    sector: "Agriculture & Fisheries",
    stir: "316790123",
    registered: "2017-09-27",
    employees: 34,
    revenue: 3_900_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Jizzax Agro Eksport MCHJ aggregates and exports fresh produce grown by contracted farms in Jizzakh Region. Export revenue is denominated in foreign currency and converted on receipt.",
  },
  {
    id: "zomin-qurilish-materiallari",
    name: "Zomin Qurilish Materiallari",
    regionId: "jizzakh",
    sector: "Construction & Materials",
    stir: "317801234",
    registered: "2015-11-16",
    employees: 47,
    revenue: 4_800_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Zomin Qurilish Materiallari MCHJ quarries and supplies gravel and dimension stone to regional construction projects. Output is sold primarily to a small number of repeat contractors.",
  },
  {
    id: "namangan-charm-poyabzal",
    name: "Namangan Charm Poyabzal",
    regionId: "namangan",
    sector: "Manufacturing",
    stir: "318912345",
    registered: "2012-04-21",
    employees: 118,
    revenue: 9_200_000_000,
    status: "Active",
    baselineRisk: "Elevated",
    description:
      "Namangan Charm Poyabzal MCHJ manufactures leather footwear for domestic retail chains. Declared employee count has fluctuated significantly between recent reporting quarters.",
  },
  {
    id: "chust-pichoq-ustaxonasi",
    name: "Chust Pichoq Ustaxonasi",
    regionId: "namangan",
    sector: "Manufacturing",
    stir: "319023456",
    registered: "2013-01-10",
    employees: 22,
    revenue: 1_800_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Chust Pichoq Ustaxonasi MCHJ produces traditional handcrafted knives sold through domestic retail and tourist channels. Production is largely artisanal with a small permanent staff.",
  },
  {
    id: "navoiy-kon-metallurgiya",
    name: "Navoiy Kon-Metallurgiya Ta'minot",
    regionId: "navoiy",
    sector: "Mining & Metallurgy",
    stir: "320134567",
    registered: "2009-03-18",
    employees: 162,
    revenue: 21_000_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Navoiy Kon-Metallurgiya Ta'minot MCHJ supplies replacement parts and consumables to regional mining operations. Filings have been submitted on schedule for the past eight quarters.",
  },
  {
    id: "navoiy-oltin-qazib-olish",
    name: "Navoiy Oltin Qazib Olish Xizmati",
    regionId: "navoiy",
    sector: "Mining & Metallurgy",
    stir: "321245678",
    registered: "2011-12-02",
    employees: 204,
    revenue: 31_600_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Navoiy Oltin Qazib Olish Xizmati MCHJ provides contract drilling and site-support services to mining operators in Navoiy Region. Revenue is largely invoice-based.",
  },
  {
    id: "qarshi-paxta-tozalash",
    name: "Qarshi Paxta Tozalash",
    regionId: "qashqadaryo",
    sector: "Agriculture & Fisheries",
    stir: "322356789",
    registered: "2010-08-25",
    employees: 174,
    revenue: 13_500_000_000,
    status: "Active",
    baselineRisk: "Elevated",
    description:
      "Qarshi Paxta Tozalash MCHJ gins and bales raw cotton sourced from regional farm clusters. Seasonal cash payments to smallholder suppliers make up a notable share of outgoing transactions.",
  },
  {
    id: "qashqadaryo-gaz-taminot",
    name: "Qashqadaryo Gaz Ta'minot",
    regionId: "qashqadaryo",
    sector: "Energy & Utilities",
    stir: "323467890",
    registered: "2012-06-06",
    employees: 91,
    revenue: 16_700_000_000,
    status: "Under Review",
    baselineRisk: "Elevated",
    description:
      "Qashqadaryo Gaz Ta'minot MCHJ maintains regional gas metering and distribution equipment under municipal contract. A billing discrepancy flagged in the prior audit remains under review.",
  },
  {
    id: "shahrisabz-qurilish-servis",
    name: "Shahrisabz Qurilish Servis",
    regionId: "qashqadaryo",
    sector: "Construction & Materials",
    stir: "324578901",
    registered: "2018-05-14",
    employees: 38,
    revenue: 3_400_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Shahrisabz Qurilish Servis MCHJ undertakes small-to-mid-scale building contracts around Shahrisabz. Most project payments are settled through escrow-style bank arrangements.",
  },
  {
    id: "samarqand-ipak-yoli-savdo",
    name: "Samarqand Ipak Yo'li Savdo",
    regionId: "samarqand",
    sector: "Wholesale & Retail Trade",
    stir: "325689012",
    registered: "2016-02-09",
    employees: 29,
    revenue: 3_950_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Samarqand Ipak Yo'li Savdo MCHJ sells souvenirs, textiles, and crafts to tourist and wholesale buyers near the historic center. Foot-traffic revenue is highly seasonal.",
  },
  {
    id: "registon-qurilish",
    name: "Registon Qurilish",
    regionId: "samarqand",
    sector: "Construction & Materials",
    stir: "326790123",
    registered: "2011-10-30",
    employees: 112,
    revenue: 15_800_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Registon Qurilish MCHJ is a general contractor active in municipal and commercial building projects across Samarqand. The company reports consistent staffing across reporting periods.",
  },
  {
    id: "samarqand-meva-konserva",
    name: "Samarqand Meva Konserva",
    regionId: "samarqand",
    sector: "Food Processing",
    stir: "327801234",
    registered: "2014-07-19",
    employees: 57,
    revenue: 4_950_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Samarqand Meva Konserva MCHJ produces jams, juices, and dried fruit for regional supermarket chains. Production scales up seasonally during the summer harvest.",
  },
  {
    id: "sirdaryo-gurunch-kombinati",
    name: "Sirdaryo Guruch Kombinati",
    regionId: "sirdaryo",
    sector: "Food Processing",
    stir: "328912345",
    registered: "2013-03-27",
    employees: 84,
    revenue: 7_100_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Sirdaryo Guruch Kombinati MCHJ hulls and packages rice grown in the Sirdaryo river basin for wholesale distribution. The mill operates on a seasonal production cycle.",
  },
  {
    id: "guliston-agro-servis",
    name: "Guliston Agro Servis",
    regionId: "sirdaryo",
    sector: "Agriculture & Fisheries",
    stir: "329023456",
    registered: "2019-04-15",
    employees: 16,
    revenue: 1_450_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Guliston Agro Servis MCHJ leases farm equipment and provides field services to smallholder growers near Guliston. The business is a recent registrant with limited filing history.",
  },
  {
    id: "termiz-chegara-logistika",
    name: "Termiz Chegara Logistika",
    regionId: "surxondaryo",
    sector: "Logistics & Transport",
    stir: "330134567",
    registered: "2015-06-08",
    employees: 73,
    revenue: 12_300_000_000,
    status: "Active",
    baselineRisk: "Critical",
    description:
      "Termiz Chegara Logistika MCHJ operates cross-border freight forwarding through the Termiz customs corridor. A significant share of declared shipments lack matching customs documentation.",
  },
  {
    id: "surxon-meva-sabzavot-eksport",
    name: "Surxon Meva-Sabzavot Eksport",
    regionId: "surxondaryo",
    sector: "Agriculture & Fisheries",
    stir: "331245678",
    registered: "2012-09-12",
    employees: 128,
    revenue: 10_600_000_000,
    status: "Under Review",
    baselineRisk: "Critical",
    description:
      "Surxon Meva-Sabzavot Eksport MCHJ exports fresh fruit and vegetables through regional border crossings. Founders are linked to several other entities registered at the same address.",
  },
  {
    id: "denov-qurilish-servis",
    name: "Denov Qurilish Servis",
    regionId: "surxondaryo",
    sector: "Construction & Materials",
    stir: "332356789",
    registered: "2017-02-28",
    employees: 45,
    revenue: 5_200_000_000,
    status: "Active",
    baselineRisk: "Elevated",
    description:
      "Denov Qurilish Servis MCHJ performs residential and light-commercial construction work in Surxondaryo Region. Cash payments account for a large share of recorded transactions.",
  },
  {
    id: "xorazm-baliq-sanoati",
    name: "Xorazm Baliq Sanoati",
    regionId: "xorazm",
    sector: "Agriculture & Fisheries",
    stir: "333467890",
    registered: "2016-08-01",
    employees: 39,
    revenue: 3_300_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Xorazm Baliq Sanoati MCHJ farms and processes freshwater fish for regional markets. Output volume is tied closely to irrigation-season water availability.",
  },
  {
    id: "urganch-savdo-majmuasi",
    name: "Urganch Savdo Majmuasi",
    regionId: "xorazm",
    sector: "Wholesale & Retail Trade",
    stir: "334578901",
    registered: "2018-01-23",
    employees: 24,
    revenue: 2_100_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Urganch Savdo Majmuasi MCHJ operates a general retail complex in central Urganch. The business reports consistent point-of-sale terminal usage in line with declared revenue.",
  },
  {
    id: "nukus-tuz-kombinati",
    name: "Nukus Tuz Kombinati",
    regionId: "qoraqalpogiston",
    sector: "Mining & Metallurgy",
    stir: "335689012",
    registered: "2010-11-05",
    employees: 97,
    revenue: 8_400_000_000,
    status: "Active",
    baselineRisk: "Elevated",
    description:
      "Nukus Tuz Kombinati MCHJ mines and processes industrial and food-grade salt from regional deposits. Utility consumption has trended above declared output over recent quarters.",
  },
  {
    id: "moynoq-ekologiya-baliqchilik",
    name: "Mo'ynoq Ekologiya-Baliqchilik",
    regionId: "qoraqalpogiston",
    sector: "Agriculture & Fisheries",
    stir: "336790123",
    registered: "2014-10-10",
    employees: 31,
    revenue: 2_750_000_000,
    status: "Suspended",
    baselineRisk: "Critical",
    description:
      "Mo'ynoq Ekologiya-Baliqchilik MCHJ processes farmed fish for regional distribution. The registration is currently suspended pending a compliance review.",
  },
  {
    id: "zamin-tech-startaplar",
    name: "Zamin Tech Startaplar",
    regionId: "tashkent-city",
    sector: "Startups & Innovation",
    stir: "337901234",
    registered: "2022-05-14",
    employees: 14,
    revenue: 850_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Zamin Tech Startaplar MCHJ develops mobile fintech products for regional banks as an early-stage, venture-backed company. Revenue is contract-based and settled entirely through bank transfer.",
  },
  {
    id: "silknet-innovatsiya",
    name: "SilkNet Innovatsiya",
    regionId: "tashkent-city",
    sector: "Startups & Innovation",
    stir: "338012345",
    registered: "2021-09-30",
    employees: 9,
    revenue: 420_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "SilkNet Innovatsiya MCHJ builds e-commerce logistics software for regional marketplaces. The company is a recent registrant with a small, fully-declared engineering team.",
  },
  {
    id: "zarafshon-farmatsevtika",
    name: "Zarafshon Farmatsevtika",
    regionId: "samarqand",
    sector: "Healthcare & Pharmaceuticals",
    stir: "339123456",
    registered: "2015-06-20",
    employees: 112,
    revenue: 12_800_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Zarafshon Farmatsevtika MCHJ manufactures generic medicines and medical supplies for regional pharmacies and hospitals. Production is subject to routine health-ministry licensing inspections.",
  },
  {
    id: "bilim-konsalting-markazi",
    name: "Bilim Konsalting Markazi",
    regionId: "tashkent-region",
    sector: "Education & Training",
    stir: "340234567",
    registered: "2018-09-03",
    employees: 21,
    revenue: 1_650_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Bilim Konsalting Markazi MCHJ runs professional certification courses and corporate training programs. Tuition is collected primarily through bank transfer and online payment.",
  },
  {
    id: "buxoro-mehmon-uy",
    name: "Buxoro Mehmon Uy Xizmatlari",
    regionId: "bukhara",
    sector: "Tourism & Hospitality",
    stir: "341345678",
    registered: "2016-04-11",
    employees: 34,
    revenue: 3_450_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Buxoro Mehmon Uy Xizmatlari MCHJ operates a small hotel and guided-tour service in the historic center of Bukhara. Revenue fluctuates seasonally with tourist arrivals, and a portion of guide fees are paid in cash.",
  },
  {
    id: "ipoteka-moliya-xizmatlari",
    name: "Ipoteka Moliya Xizmatlari",
    regionId: "tashkent-city",
    sector: "Financial Services",
    stir: "342456789",
    registered: "2017-01-30",
    employees: 58,
    revenue: 9_200_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Ipoteka Moliya Xizmatlari MCHJ provides mortgage brokerage and micro-lending services to retail clients. The company is subject to central bank reporting requirements.",
  },
  {
    id: "poytaxt-kochmas-mulk",
    name: "Poytaxt Ko'chmas Mulk",
    regionId: "tashkent-city",
    sector: "Real Estate",
    stir: "343567890",
    registered: "2013-11-08",
    employees: 26,
    revenue: 18_900_000_000,
    status: "Active",
    baselineRisk: "Elevated",
    description:
      "Poytaxt Ko'chmas Mulk MCHJ brokers residential and commercial property sales across Tashkent. A significant share of transaction value is settled outside formal escrow arrangements.",
  },
  {
    id: "fargona-aloqa-tarmoqlari",
    name: "Farg'ona Aloqa Tarmoqlari",
    regionId: "fergana",
    sector: "Telecommunications",
    stir: "344678901",
    registered: "2011-03-22",
    employees: 87,
    revenue: 15_300_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Farg'ona Aloqa Tarmoqlari MCHJ operates regional internet and fixed-line telecom infrastructure under a formal license. Billing is fully automated and bank-reconciled.",
  },
  {
    id: "ohanrabo-media-grup",
    name: "Ohanrabo Media Grup",
    regionId: "tashkent-city",
    sector: "Media & Entertainment",
    stir: "345789012",
    registered: "2020-02-14",
    employees: 17,
    revenue: 1_950_000_000,
    status: "Active",
    baselineRisk: "Moderate",
    description:
      "Ohanrabo Media Grup MCHJ produces digital advertising content and manages influencer marketing campaigns. Revenue includes a mix of invoiced contracts and direct platform payouts.",
  },
  {
    id: "ishonch-yuridik-xizmatlari",
    name: "Ishonch Yuridik Xizmatlari",
    regionId: "tashkent-city",
    sector: "Professional Services",
    stir: "346890123",
    registered: "2014-08-19",
    employees: 12,
    revenue: 1_100_000_000,
    status: "Active",
    baselineRisk: "Low",
    description:
      "Ishonch Yuridik Xizmatlari MCHJ provides legal and accounting advisory services to small and mid-size businesses. Client billing is invoiced and settled through bank transfer.",
  },
  {
    id: "andijon-avto-savdo",
    name: "Andijon Avto Savdo",
    regionId: "andijan",
    sector: "Automotive & Machinery Trade",
    stir: "347901234",
    registered: "2012-07-05",
    employees: 64,
    revenue: 21_400_000_000,
    status: "Active",
    baselineRisk: "Elevated",
    description:
      "Andijon Avto Savdo MCHJ resells passenger vehicles and spare parts sourced from regional manufacturers. A large share of used-vehicle transactions are settled in cash.",
  },
]

export function getBusiness(id) {
  return BUSINESSES.find((business) => business.id === id)
}

export function getBusinessesByRegion(regionId) {
  return BUSINESSES.filter((business) => business.regionId === regionId)
}
